---
- name: Ensure directory for backup script exists
  file:
    path: "{{ backups_role_script_path }}"
    state: directory
    owner: "{{ backups_role_user }}"
    group: "{{ backups_role_group }}"
    mode: 0775

- name: Copy backup script
  template:
    src: backups.sh.j2
    dest: "{{ backups_role_script_path }}/backups.sh"
    owner: "{{ backups_role_user }}"
    group: "{{ backups_role_group }}"
    mode: 0775

- name: Ensure directory for backups temporary data exists
  file:
    path: "{{ backups_role_last_backup_path }}"
    state: directory
    owner: "{{ backups_role_user }}"
    group: "{{ backups_role_group }}"
    mode: 0775

- name: Ensure postgresql role (user) for backups exists with read only access
  postgresql_user:
    db: "{{ backups_role_db_name }}"
    name: "{{ backups_role_postgresql_user }}"
    password: "{{ backups_role_postgresql_user_passwd }}"
    priv: "CONNECT/{{ backups_role_db_name }}:SELECT"

- name: Let backup user to use `{{ backups_role_sudoers_cmd_pattern }}` as root
  lineinfile:
    path: /etc/sudoers
    state: present
    # Pattern to match the line
    regexp: '^{{ backups_role_user_name }} ALL=(root)'
    # Actual line to exist in the file
    line: "{{ backups_role_user_name }} ALL=(root) NOPASSWD: {{ backups_role_sudoers_cmd_pattern }}"
    validate: '/usr/sbin/visudo -cf %s'

- name: Install restic and configure restic repository
  vars:
    restic_version: "{{ backups_role_restic_version }}"
    restic_repos:
      - name: "{{ backups_role_restic_repo_name }}"
        url: "{{ backups_role_bucket_url }}"
        password: "{{ backups_role_restic_password }}"
        remote_credentials:
          # See README.md for an explanation
          # we cross app and account credentials here.
          b2_account_id: "{{ backups_role_b2_app_key_id }}"
          b2_account_key: "{{ backups_role_b2_app_key }}"
        jobs:
          - command: "{{ backups_role_cmd_script }}"
            at: "{{ backups_role_cron_job_at }}"
            user: "{{ backups_role_user_name }}"
    restic_user: "{{ backups_role_restic_user }}"
    restic_cron_stdout_file: "{{ backups_role_restic_cron_stdout_file }}"
    restic_cron_stderr_file: "{{ backups_role_restic_cron_stderr_file }}"
    
  include_role:
    name: vendor/paulfantom.restic
